name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install TF library 1.15.0 alpha
    - name: extra libraries
      run: |
        export PATH=$PATH:$GITHUB_WORKSPACE/bin
        arduino-cli lib install Arduino_TensorFlowLite@1.15.0-ALPHA


    - name: test platforms
      run: python3 ci/build_platform.py pybadge cpb

    #- name: clang
    #  run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r . 

    #- name: doxygen
    #  env:
    #    GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
    #    PRETTYNAME : "Adafruit TFLite Library"
    #  run: bash ci/doxy_gen_and_deploy.sh
